;; Q: The sine of an angle (specified in radians) can be computed by making use of the approximation sin(x) =~ x if x is sufficiently small, and the trigonometric identity
;;
;; sin(r) = 3sin(r/3)-4sin(r/3)^3
;; to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered ‘‘sufficiently small’’ if its magnitude is not greater than 0.1 radians.) These ideas are incorporated in the following procedures:

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))

;; a. How many times is the procedure p applied when (sine 12.15) is evaluated?
;; b. What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?

;; A:
;; a: Replacement:
(sine 12.15)
(p (sine 4.05))
(p (p (sine 1.35)))
(p (p (p (sine 0.45))))
(p (p (p (p (sine 0.15)))))
(p (p (p (p (p (sine 0.05))))))
(p (p (p (p (p 0.05)))))
; ...

;; p is applied 5 times when (sine 12.15) is evaluated
;; b:
;; Space(a) = O(a)
;; Because space is determined by the depth of the calls, it grows linearly with a
;; It's really Space(a) =~ a/3 + 1

;; Steps(a) = O(a)
;; It's really Steps(a) =~ 9(a/3 + 1)

;; Above is the answer I came up with on my own. I find out that this is incorrect, and it's because our space and steps include a/3. So both actually grow logarithmically, that is,
;; Space(a) = O(log(a))
;; Steps(a) = O(log(a))
;; This is better than the linear growth that I assumed.
;; http://www.billthelizard.com/2009/12/sicp-exercise-115-calculating-sines.html
;; "The space (or time) growing by addition as the input grows by multiplication is the hallmark of logarithmic growth."
